export const DEFAULT = 'DEFAULT_ACTION'

export const LOGIN_BEGIN = 'LOGIN_BEGIN'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'

export const REGISTRATION_BEGIN = 'REGISTRATION_BEGIN'
export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS'
export const REGISTRATION_FAILURE = 'REGISTRATION_FAILURE'

export const GET_USER_BEGIN = 'GET_USER_BEGIN'
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS'
export const GET_USER_FAILURE = 'GET_USER_FAILURE'

export const SEND_CODE_BEGIN = 'SEND_CODE_BEGIN'
export const SEND_CODE_SUCCESS = 'SEND_CODE_SUCCESS'
export const SEND_CODE_FAILURE = 'SEND_CODE_FAILURE'

export const UPDATE_PROFILE_BEGIN = 'UPDATE_PROFILE_BEGIN'
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS'
export const UPDATE_PROFILE_FAILURE = 'UPDATE_PROFILE_FAILURE'

export const UPDATE_DRAWER = 'UPDATE_DRAWER'

export const SCRATCH_OFFER_BEGIN = 'SCRATCH_OFFER_BEGIN'
export const SCRATCH_OFFER_SUCCESS = 'SCRATCH_OFFER_SUCCESS'
export const SCRATCH_OFFER_FAILURE = 'SCRATCH_OFFER_FAILURE'

export const ANAGRAM_BEGIN = 'ANAGRAM_BEGIN'
export const ANAGRAM_SUCCESS = 'ANAGRAM_SUCCESS'
export const ANAGRAM_FAILURE = 'ANAGRAM_FAILURE'

export const UPDATE_POINT_BEGIN = 'UPDATE_POINT_BEGIN'
export const UPDATE_POINT_SUCCESS = 'UPDATE_POINT_SUCCESS'
export const UPDATE_POINT_FAILURE = 'UPDATE_POINT_FAILURE'

export const UPDATE_USER_POINT_BEGIN ="UPDATE_USER_POINT_BEGIN"
export const UPDATE_USER_POINT_SUCCESS ="UPDATE_USER_POINT_SUCCESS"
export const UPDATE_USER_POINT_FAILURE ="UPDATE_USER_POINT_FAILURE"